// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMu2HOxRloczRXwu2vyYc2HmXfsW2L6c',
    appId: '1:572880722580:web:dca1d67ccde1cf55aab281',
    messagingSenderId: '572880722580',
    projectId: 'minimal-social-app-e6394',
    authDomain: 'minimal-social-app-e6394.firebaseapp.com',
    databaseURL: 'https://minimal-social-app-e6394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'minimal-social-app-e6394.appspot.com',
    measurementId: 'G-Y9XC32MTCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mtxVd8EjUH-e7Bfg4xQNiNCyK1BmU54',
    appId: '1:572880722580:android:e73e3b4b5c430567aab281',
    messagingSenderId: '572880722580',
    projectId: 'minimal-social-app-e6394',
    databaseURL: 'https://minimal-social-app-e6394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'minimal-social-app-e6394.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPg7XOdz9qcG13vS7MyS98I_dur7rlqM',
    appId: '1:572880722580:ios:ca04dd95abe3c522aab281',
    messagingSenderId: '572880722580',
    projectId: 'minimal-social-app-e6394',
    databaseURL: 'https://minimal-social-app-e6394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'minimal-social-app-e6394.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPg7XOdz9qcG13vS7MyS98I_dur7rlqM',
    appId: '1:572880722580:ios:ca04dd95abe3c522aab281',
    messagingSenderId: '572880722580',
    projectId: 'minimal-social-app-e6394',
    databaseURL: 'https://minimal-social-app-e6394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'minimal-social-app-e6394.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKMu2HOxRloczRXwu2vyYc2HmXfsW2L6c',
    appId: '1:572880722580:web:e54d4c8694a7879caab281',
    messagingSenderId: '572880722580',
    projectId: 'minimal-social-app-e6394',
    authDomain: 'minimal-social-app-e6394.firebaseapp.com',
    databaseURL: 'https://minimal-social-app-e6394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'minimal-social-app-e6394.appspot.com',
    measurementId: 'G-SF9M8N6JF8',
  );
}
